### ISSUE TITLE
Add requirements file for ble_listener.py and cps_monitor.py - error when running

### ISSUE THREAD

**Issue by johannesparschau** [johannesparschau/bicycle_power_meter#8]
```
Error when running cps_monitor.py:
Traceback (most recent call last): File "C:\Projects\power_meter_cleat\cps_monitor.py", line 66, in <module> 
root = tk.Tk() 
File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\tkinter_init_.py", line 2459, in init 
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) 
~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
C:/Projects/power_meter_cleat/.venv/Lib/site_packages/Tcl C:/Users/<user>/AppData/Local/Programs/Python/Python313/lib/tcl8.6 C:/Users/<user>/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/<user>/AppData/Local/Programs/lib/tcl8.6 C:/Users/<user>/AppData/Local/Programs/Python/library C:/Users/<user>/AppData/Local/Programs/library C:/Users/<user>/AppData/Local/Programs/tcl8.6.14/library C:/Users/<user>/AppData/Local/tcl8.6.14/library

This probably means that Tcl wasn't installed properly.
```

**Comment by johannesparschau** [comment]
Assumed requirements added to Readme: bleak, matplotlib, tkinter. Assumption that asyncio is automatically installed when setting up a virtual Python environment
